export const PAGE_REQUEST = 'PAGE_REQUEST';
export const PAGELIST_REQUEST_SUCCESS = 'PAGELIST_REQUEST_SUCCESS';
export const PAGE_REQUEST_SUCCESS = 'PAGE_REQUEST_SUCCESS';
export const PAGE_REQUEST_FAIL = 'PAGE_REQUEST_FAIL';
export const RESET = "RESET";